version: "3.9"

services:
  react-app:
    container_name: frontend
    restart: on-failure
    build: ./
    volumes:
      - ./src:/app/src
      - "/app/node_modules"
    ports:
      - "3000:3000"
    stdin_open: true
    command: >
      sh -c "npm start"
